"""empty message

Revision ID: 23fdf3f3b252
Revises: ce0587541ce2
Create Date: 2018-05-04 16:00:12.732551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23fdf3f3b252'
down_revision = 'ce0587541ce2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tweet_count',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('for_date', sa.DateTime(), nullable=True),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tweet_count')
    # ### end Alembic commands ###
