"""empty message

Revision ID: ce0587541ce2
Revises: 7809f6ae50f5
Create Date: 2018-05-04 15:07:08.100897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce0587541ce2'
down_revision = '7809f6ae50f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tweet_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tweet_count',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('count', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
